### ISSUE TITLE
Re-check case connect dApp when have network is disconnected

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#1127] opened 2023-04-05 04:20 UTC
**Description of the task**
Re-check case connect dApp when have network is disconnected
- Check with "connect.subwallet.app"

Actual: When have an active network from dApp and the network is disconnected (unable to connect provider) then:
- Do not connect the wallet

**Comment by Sokol142196** [comment] 2024-09-09 11:33
Unable to reproduce the issue on the current extension (v1.2.28) -> Close this issue

**Closed by Sokol142196** 2024-09-09 11:33 UTC
