### ISSUE TITLE
Custom Network, Custom Endpoint

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#36] opened 2022-03-24 08:54 UTC
## Problems
SubWallet not only work as **wallet** but aslo contain many features of DApp and connect many Dotsama networks. Network list and endpoint in SubWallet is fixed, and extension will connect all to get data, this way has some problems below:
- User not really need to connect all of network, connect to networks that users don't own assets are wasted because it consume ram and cpu for maintain these connection.
- Not all of networks endpoints work well, some of them are not stable that make some features can not respond or respond intime.
- We also want to integrate "Light client", one allow user connect direct to block chains by peers-to-peers protocol, so we need some features to user select which method that they want.
- There are no way for user add new networks or test networks, they need to wait ultil subwallet support.
- We need something to handle which features should be enable to the network.

## Solutions
To solve above problems we have some idea about custom endpoint and custom new network:
- We maintain a `NetworkMap` in background that mixed of predefined data and custom data.
  - Predefine networks has static key and contain some static information that defined in `networks.ts`
  - Custom network has unique key that is auto generated and cannot bechanged after added.
  - We mixed all of them and persist all into browser storage.
- Each network in `NetworkMap` has some static and dynamic data
  - `NetworkKey` is predefined or generated and can not be change after add network.
  - Predefined endpoints list (for predefined network only) that contain list of predefined endpoint and light client.
  - Custom endpoint litst that contain all user defined endpoint. User can define more than one endpoint to each custom network.
  - With predefined network allow to change only custom endpoint, other properties will be fixed
- User can select what network thay want to active and provider endpoint they want, SubWallet will connect and get information from these network only.
- The information will be reload depend that what changed in network map.
- Add information about which features each network should be support, which options should be use to these methods.

### Network Properties
```typescript
export interface NetworkJson {
  // General Informations
  key: NetworkKey, // Key of network in NetworkMap
  chain: string; // Name of the network
  icon?: string; // Icon name, available with known network

  // Provider Informations
  predefinedProviders: Record<string, string> // Predefined provider map
  customProviders: Record<string, string> // Custom provider map, provider name same with provider map
  nftProvider: string // Should be same with provider if is not defined
  providerKey: NetworkKey, // Current provider key
  provider: string; // Current provider
  providerMode: 'http' | 'ws' // Current provider mode, compute depend on provider protocol. the feature need to know this to decide use subscribe or cronjob to use this features.

  // Metadata get after connect to provider
  paraId?: number;
  genesisHash: string;
  groups: NetWorkGroup[];
  ss58Format: number;
  chainType?: 'substrate' | 'ethereum';
  crowdloanUrl?: string;

  // Ethereum informations for predefine network only
  isEthereum?: boolean; //Only show network with isEthereum=true when select one EVM account

  // Native token information
  nativeToken?: string;
  decimals?: number;

  // Other informations
  active: boolean, // Network is active or not
  coinGeckoKey: string, // Provider key to get token price from CoinGecko
  blockExplorer?: string, // Link to block scanner to check transaction with extrinsic hash
  dependencies: NetworkKey[] // Auto active network in dependencies if current network is activated

  // Support features
  getBalanceMethod?: 'SUTSTRATE' | 'SUBSTRATE_TOKEN' | 'EVM' | 'ERC20'; // How to get balance
  sendFundMethod: 'SUBSTRATE', 'EVM'
  getTokenMethod?: 'SUBSTRATE_TOKENS', 'ERC20'; // How to get tokens
  sendTokenMethod?: 'SUBSTRATE', 'ERC20'
  sendXCMTokens?: 'SUBSTRATE_XTOKENS', 'EVM_XTOKENS', 'RAW_XCM';
  getStakingMethod?: 'SUBSTRATE';
  getCrowdloanMethod?: 'POLKADOT', 'DOTSAMA', 'CUSTOM' // This method is required paraId, custom network can not select custom method
  getNFTMethod?: 'ERC721' | 'CUSTOM';
  sendNFTMethod?: 'ERC721' | 'CUSTOM'

  // Methods
  getDotsamaAPI?: ApiPromise;
  getWeb3API?: Web3;
  getNFTWeb3API?: Web3;
}
```

### Network methods
- `getNetworkMap(): Record<NetworkKey: NetworkInfo>`: Return network map and mixed data between predefined data and new data in network list
- `subcribeNetworkMap(callback(networkMap: Record<NetworkKey: NetworkInfo>, changes: Record<NetworkKey: NetworkChangeType>): }): Record<NetworkKey: NetworkInfo>` Return network map and subscribe network changes.
- `updateNetwork(network: NetworkInfo): UpdateNetworkResult`: Update a network in network map

### Network events
Here is input of callback for subscribe network when have any change from network map
- `networkMap: Record<NetworkKey: NetworkInfo>`: Full networks map
- `changeMap: Record<NetworkKey: NetworkChangeType>`: What changes with network list
  - `NetworkChangeType`: `'add', 'remove', 'update'`
Reference features need to subscribce these change to decide what to do. For example:
- Background should be create new subscribe new network and show their balance when new network is actived

### Research
- [x] Design struct of new network map
   - [x] Listing properties
   - [x] Suitable for migration
   - [x] Suitable with current web3 implement (web3 only allow for predefined network only with specialFeatures )
- [x] Design way to interact with network map
  - [x] How to mixed predefined network data with exsisted in the furture
  - [x] What will occcur when change predefined data?
  - [x] What will occcur when network infor change?
    - Type of changes
    - Changed data
    - Full `NetworkMap`
  - [x] Design for some special changes: with some case provider eg: Astar connect interact with NFT via substrate endpoint and connect to ERC20 tokens via EVM.
    - NFT Provider: only show to predefined network

### Impletemenmt new network config
- [x] Build predefined network map
  - [x] Get data from Pokadot{.js} App
  - [x] Update predefined network map with some special key like moonbase, astarEvm, shidenEVM
  - [x] Update all into predefinedNetworks.json
- [x] Create browser store to save `NetworkMap`
- [x] Update Koni State
  ```typescript

  // Use for cache network map
  private networkMap: Record<NetworkKey, NetworkJson>;

  // Create networkSubject
  private networkMapSubject = new Subject<Record<NetworkKey, NetworkChange>>();

  public getNetworkMap = async (useCache = true): Promise<Record<NetworkKey, NetworkJson>> => {
    if (!this.networkMap || !useCache) {
      // Get predefined network map
      const predefinedNetworkMap: Record<NetworkKey, NetworkJson>;
      // Get network map in chrome store
      const storedNetworkMap: Record<NetworkKey, NetworkJson>;

      // Deep copy predefinedNetworkMap
      const result: Record<NetworkKey, NetworkJson> = JSON.parse(JSON.stringify(predefinedNetworkMap));

      // Todo: Add new item from stored storedNetworkMap if not exist
      // Todo: Only replace these props with predefined networks: customProviders, providerKey
      // Todo: Compute provider, providerMode, NFT Provider

      this.networkMap = result;
    }

    return this.networkMap;
  };

  public setNetworkMap = async (networkMap: Record<NetworkKey, NetworkJson>) => {
    this.networkMap = networkMap;
    // Todo: store networkMap
  }

  public subscribeNetworkMap = (networkMap: Record<NetworkKey, NetworkJson>, callback: (changes: Record<NetworkKey, NetworkChange>) => void) => {
    return this.networkMapSubject.subscribe({
      next: async (changes: Record<NetworkKey, NetworkChange>) => {
        const networkMap = await this.getNetworkMap();

        callback(networkMap, changes);
      }
    });
  };

  public async validateNetworkBasic (network: NetworkJson, checkProviderConnection = true) {
    const errors: string[] = [];

    // Todo: Validate info types
    // Todo: Prevent inject script
    // Todo: Validate providers
    // Todo: Check provider connections

    return errors;
  }

  // Add or update network
  public upsertNetwork = async (network: NetworkJson, checkProviderConnection = true): Promise<string[]> => {
    // Check key available
    const [validateErrors, networkMap] = await Promise.all([this.validateNetworkBasic(network, checkProviderConnection), this.getNetworkMap()]);

    const changes: Record<NetworkKey, NetworkChange> = {};
    let networkKey = network.key;

    if (networkKey) {
      const existed = networkMap[networkKey];
      if (!existed) {
        // Todo: Add error to validate error
      }
      changes[networkKey] = 'update';
    } else {
      networkKey = ...// Random unique id start with 'network_'
      changes[networkKey] = 'add';
    }

    if (validateErrors.length > 0) {
      return validateErrors;
    }

    networkMap[networkKey] = network;
    await this.setNetworkMap(networkMap);

    this.networkMapSubject.next(changes);
    return validateErrors;
  };

  public removeNetwork = async (networkKey: NetworkKey) => {
    const validateErrors: string[] = [];
    const networkMap = await this.getNetworkMap();

    // Todo: check network key is exsited or not
    // Todo: validate dependencies networks
    // Todo: remove item from network map

    await this.setNetworkMap(networkMap);

    const changes: Record<NetworkKey, NetworkChange> = {};

    changes[networkKey] = 'remove';

    this.networkMapSubject.next(changes);

    return validateErrors;
  };
  ```
- [x] Update new metadata fields if when first time when success to connect with provider
- [x] Improve interface to get API with networkKey from network map
  - Auto create connection when select method get API
  - Remove if timeout
  - Reconnect when disconnect...
- [x] Create message handle in `Extension.ts` and `messsaging.ts`
  - getNetworkMap
  - subscribeNetworkMap
  - validateNetwork
  - upsertNetwork
  - removeNetwork
- [x] #119

### Migrate to new network config in SubWallet features (replace use of const `NETWORKS` in `endpoinds.ts` and add subscrible the changes of networks) 
Each below method need to implement new way to `getNetworkMap()` and subscribe the changes of `networkMap` to response new data for it's subscriptions.
- [x] Get Balance
- [x] Send Fund
- [x] Get Staking
- [x] Get Crowdloan
- [x] Get NFT
- [x] Send NFT
- [x] Transfer API
- [x] Update extension popup (UI) - Only show activated networks (on the network menu, balance, transaction history, ...)

### Implement UI of network config
- [x] Network List Screen
- [x] Network Detail Sccreen
  - [x] Validate when saving network for extension Popup

**Comment by lw-cdm** [comment] 2022-03-28 11:48
Todo list:
- Abstract network config, network config will be formed by:
	- Origin config defined in endpoints.ts
	- User custom network config
- Detail of network config:
	- key: 
		- Require
		- Display name on UI: Network Key
		- Indentification of each network
	- chain:
		- Require
		- Display name on UI: Display name
		- For display network name on UI
	- genesisHash:
		- Require
		- Display name on UI: genesis Hash
		- Is the genesis Hash of the network	
	- ss58Format:
		- Require
		- Display name on UI: Network prefix
		- Reformat the origin address (unless the address format is Ethereum)
	- isEthereum	
		- Option: default is false
		- Determind if the network supports Ethereum
	- icon:
		- Option
		- Display name on UI: Icon type
		- One of these options:
			- substate
			- polkadot
		- Reformat the avatar created by the origin address.
		- Will not show if isEthereum is true
	- groups:
		- Require
		- Display name on UI: Network group
		- One of these options:
			- RELAY_CHAIN: Relay Chain
			- POLKADOT_PARACHAIN: Polkadot Parachain 
			- KUSAMA_PARACHAIN: Kusama Parachain 
			- MAIN_NET: Mainnet
			- TEST_NET: Testnet
	- paraId:
		- Option
		- Display name on UI: Para Id	
		- Only shows if groups is ether POLKADOT_PARACHAIN or KUSAMA_PARACHAIN
	- nativeToken
		- Require
		- Display name on UI: Native Token		
		- Token of the network
	- crowdloanUrl:
		- Option
		- Display name on UI: Crowdloan page URL		
		- Only shows if groups is ether POLKADOT_PARACHAIN or KUSAMA_PARACHAIN		
	- decimals
		- Require	
		- Display name on UI: Decimals
		- For display and calculate balance.		
	- providerDefinitions:
		- Require
		- Map type: "Display name on UI (unique)" - "The URL of the RPC"
		- Define the provider user can choose
	- provider
		- Require
		- Type string, value is a key of the map providerDefinitions
		- We compare provider value with providerDefinitions key to get RPC URL of the network
	- scanExplorer:
		- Option
		- Display name on UI: Scan Explorer Endpoint
		- The endpoint URL of the Scan Explorer (for display transaction history)
- Create browser store to save network config
- Create browser store to save activated networks 
- Solve asynchrony problem when toggle networks 
- Create messages to update network configs
- Create messages to toggle networks
- UI:
	- Create list screen
	- Create detail screen
		- If the network is predefined, only allow user to choose the provider
- Update extension background
	- Balance: only calculate the balance of activated networks
	- Update logic related to providerDefinitions and provider
	- Update logic related to send fund
- Update extension popup (UI)
	- Only show activated networks (on the network menu, balance, transaction history, ...)
- Validate when saving network for extension Background
- Validate when saving network for extension Popup
- Create a screen to notify user if all network are disable  
- Create popup indicate Metadata is no longer supported
- Update libs, pulgins to latest version

**Comment by lw-cdm** [comment] 2022-04-12 05:23
I think we will need provider status (to indicate that the provider is connected, loading, disconnect, ... ) and reload provider feature (allow user to reload the network if having problem with it).

**Comment by NamPhamc99** [comment] 2022-04-23 09:30
Progress update:
- Implemented Custom Network UI
- Implemented State for NetworkMap and ApiMap
- Implemented upsert, disable, enable networks
- Cron job for checking network connection status
- Checking provider when adding or update network
- Only show active networks and connection status on NetworkMenu
- Subscription for NetworkMap and ApiMap

**Comment by NamPhamc99** [comment] 2022-04-23 10:28
Test cases:

- [ ] Merge predefined networks with custom networks
- [ ] Update predefined networks
- [ ] Create new network
- [ ] Change provider for a network
- [ ] Add a custom provider for a network
- [ ] Disable/Enable network

**Comment by NamPhamc99** [comment] 2022-04-27 06:57
Related UI components to be tested:

- Metadata chain
- Signing components
- Account QR Modal
- AccountInfo
- Crowdloan components
- Ledger related components (useLedger, legerChains, ImportLedger)

**Comment by NamPhamc99** [comment] 2022-04-29 10:55
Related functionalities to be tested (both substrate/ evm account):
- Token balance
- Token price
- Send/Receive token
- Show NFT
- Send/Receive NFT
- Staking balance

**Comment by NamPhamc99** [comment] 2022-05-05 02:50
Note:

- Do more research on light client to improve first-time loading performance

**Comment by sokol142** [comment] 2022-05-05 07:46
Some issues:
1. Can't connect "RMRK test" network when click on toggle
![BugConnectNetwork](https://user-images.githubusercontent.com/102292476/166881108-9236f9e8-6480-4362-9d83-33a0440fef37.gif)

2. Unable to search network by network name containing uppercase characters (example: Kusama)
![BugConnectNetwork_search](https://user-images.githubusercontent.com/102292476/166881526-489fc398-76ad-472e-bc30-01352490faa2.gif)

**Comment by NamPhamc99** [comment] 2022-05-17 09:36
@Quangdm-cdm Please check the color bug on Ethereum chain Id Input, it's the InputWithLabel with disabled = true

**Comment by sokol142** [comment] 2022-05-18 08:19
Version test: Build (18052022)
Please check issues:

- [ ] Can't update Network Name, ParaID, More Options
- Actual: 
      + Case: Update ParaID, More Options fields then Save configure => Button Save disable -> can't Save configuration
      + Change Provider URL then update ParaID, More Option & Save configure => Save successfully but ParaID & More Options fields not change
- Expected: If all data is valid then enable Save button & updated successfully
![image](https://user-images.githubusercontent.com/102292476/168985363-2dc9b9c9-a229-43ba-b031-21847546c756.png)

- [ ] Bug when send fund/donate with New network
![Bug_36_sendfund](https://user-images.githubusercontent.com/102292476/168990502-0c1e39b3-5d36-49d2-970c-47dcea317fec.gif)

- [ ] Infinity loading in case User stand on NFT tab & disconnect Network
![Bug_36_loadNFT](https://user-images.githubusercontent.com/102292476/168991897-05ed30c6-53a4-4197-9242-d1246f95d33a.gif)

**Comment by NamPhamc99** [comment] 2022-05-19 07:29
@lw-cdm Please remove the usage of getBackgroundPage() from koni-ui
Remove the following usages:
const bWindow = chrome.extension.getBackgroundPage() as BackgroundWindow;
const { keyring } = bWindow.pdotApi;
const { apisMap } = bWindow.pdotApi;
Note: Be careful with some of the components being used by NFT transferring (located at /Nfts/transfer/components)

**Comment by NamPhamc99** [comment] 2022-05-19 08:55
Support EVM token functionalities when add custom EVM chain (transfer, see balance, see NFT, transfer NFT)

**Comment by NamPhamc99** [comment] 2022-05-19 09:06
Update usage of paraId, blockExplorer, crowdLoanUrl, coinGeckoKey

**Comment by NamPhamc99** [comment] 2022-05-19 09:17
@lw-cdm Support transferring native token when adding custom network (might fail due to RPC functions not supported)

**Comment by sokol142** [comment] 2022-05-20 05:28
pls check issues:

- [ ] Display all token on Send Fund/Donate screen although disconnect network, user must be reload page
- Expected: Automatically update list token when disconnect network
![bug_36_listtoken](https://user-images.githubusercontent.com/102292476/169453950-b9371e78-147a-430b-8e9a-796e2d22e976.gif)

- [ ] Can't remove value of the ParaID, More Option fields when update configure network

- [ ] Can't update Network after add other provider url successfully
![bug_36_updateProvideURL](https://user-images.githubusercontent.com/102292476/169455403-317a1b02-e60e-437b-9cec-8d1ff9aa52cd.gif)

- [ ] Still display "Connecting to the provider..." when user input valid Provider URL
![image](https://user-images.githubusercontent.com/102292476/169456105-2fe9c799-5e95-46fb-a23f-b1b4c8963185.png)

**Comment by sokol142** [comment] 2022-05-25 11:33
Version test: Build ngày 25/05/2022

- [ ] Navigate to incorrect screen when click on Custom Network on List Network screen
Steps to reproduce:
1. Go to Configure Network screen
2. Save Configure successfully
3. Back to Homepage or go to other screen
4. Click on Network Select box
5. Then click on Custom Network button 
6. Observe screen displaying
Actual: Display Configure Network same as Step 1
Expected: Display Network Settings screen


![Image](https://user-images.githubusercontent.com/102292476/170249007-b349b364-efb4-4680-86fd-31b37c96222c.gif)

**Comment by sokol142** [comment] 2022-05-26 09:23
Improve some experiences:

- [ ] List Chain on the import token screen should only show the active network
![image](https://user-images.githubusercontent.com/102292476/170448989-05655f5f-c7e2-48e1-9439-9003ae977f07.png)
- [ ] Disable button Save Configure Network when creating new provider URL
![image](https://user-images.githubusercontent.com/102292476/170449311-f9b355d7-2b27-4d58-89e3-c43b4bafc589.png)

**Comment by NamPhamc99** [comment] 2022-05-27 06:56
Test cases when users upgrade new version:
1. Upgrade from old version without custom network
  - Expectation: Show network selection screen at home screen
2. Merging networks from older version to a newer version
  - Merge a predefined network with customized settings
  - Merge 2 networks with the same genesisHash (a custom network added in the old version, then subwallet supports it in the new version)
  - Keep custom networks when updating versions

**Closed** 2022-05-31 10:38 UTC
Labels: enhancement
