### ISSUE TITLE
Some problems related to NFT function

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#105] opened 2022-04-05 03:03 UTC
**Describe the bug**

- [x] Still display NFT Collection on New Network even though this Network have no NFT
**To Reproduce**
1. Stand on NFT detail screen
2. Switch Network
**Actual**: Still display NFT Collection on New Network even though this Network have no NFT
**Expected behavior**: Back to List NFT Collection screen (_my suggestion_)
![image](https://user-images.githubusercontent.com/102292476/161670780-0e16ccb8-fbc8-4851-86d4-2c8c70bf008a.png)

- [x] Display the loading screen
**To Reproduce**
1. Stand on Send NFT in expand screen
2. Open the wallet in popup screen
3. On the popup screen, do switch Account
4. Observe wallet in the expand screen
**Actual**: Display the loading screen
**Expected behavior:** Navigate to List NFT Collection of the account
![image](https://user-images.githubusercontent.com/102292476/161671139-3100eba0-fb94-4903-8e92-53ad9f92bb8f.png)

- [x] Still display Send NFT, then click on Send NFT, Fees value is incorrect
**To Reproduce**
1. Stand on Send NFT
2. Input valid data for the "Send to address" field
3. Switch Network
4. Click on Send button and observe fees value of the Authorize screen
**Actual:** Still display Send NFT, then click on Send NFT, Fees value is incorrect
**Expected behavior**: Redirect to this NFT's network
![image](https://user-images.githubusercontent.com/102292476/161670989-7b6201d4-f9d1-4650-81a0-170ca5af341a.png)

**Comment by NamPhamc99** [comment] 2022-04-06 09:58
Display the loading screen
- The loading screen shows up when the RPC connection is in progress, it's not a bug
- Changing network during transferring is a bug, i suggest checking network when the Send button is hit and stop user from proceeding to the next step
 @sokol142

**Comment by hieudd** [comment] 2022-04-07 02:49
@NamPhamc99 pls add the NFT name in to NFT screen like NFT collection name

**Comment by sokol142** [comment] 2022-04-07 03:24
> * The loading screen shows up when the RPC connection is in progress, it's not a bug
**Case: Switch Account**
But the loading screen always shows?
- This problem incase you do switch account successful in the popup mode -> In the expand mode, NFT is not existed and the loading screen always show (you observe this problem in the attached file) => May you consider it?

**Case: Switch Network**
- I agree with your suggestion.
@NamPhamc99 
![SwitchAccount](https://user-images.githubusercontent.com/102292476/162113929-134e5b65-3990-4715-a35d-f977a9aade16.gif)

**Comment by NamPhamc99** [comment] 2022-04-07 04:47
Case: Switch Account
Fix: redirect users back to NFT page, cancel the sending process
@sokol142

**Comment by sokol142** [comment] 2022-04-08 05:36
@NamPhamc99 
- Sub-task: 1, 2: OK
- Add the NFT Name: OK
- Sub-task 3: Fix issue in case Switch to "Allow use on any chain"
(Actual: The loading screen always show
Expect: I suggest display message warning: "Please change to [NFT's Network]" or display message warning like message in the Send Fund screen)
![issue_105](https://user-images.githubusercontent.com/102292476/162370694-b86f5560-3113-4cdc-ab45-af3a01a33b2d.gif)

**Closed** 2022-04-08 09:30 UTC
Labels: bug
