### ISSUE TITLE
WebApp - Error page in case enable config Camera access for QR on local

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2138] opened 2023-11-04 05:46 UTC
**Describe the bug**
Error page in case enable config Camera access for QR on local

Version test: http://192.168.10.156:9000/home/tokens

**To reproduce the bug**
Pre-condition: Config Camera access for QR is turn off

Steps:
1. Go to Import by QR code 
2. Click on Scan the QR code -> Go to setting
3.  Enable config Camera access and observe the displayed screen

Actual: Error page 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/1bc8ce71-c1b3-4e83-a42e-004c90ed4116)

**Comment by Sokol142196** [comment] 2023-11-09 03:53
@ThaoNguyen998 please verify this bug on official version

**Comment by Sokol142196** [comment] 2023-11-09 04:18
@saltict @S2kael This error only occurs locally, please check again to find the cause to avoid possible errors

**Comment by Thiendekaco** [comment] 2023-11-29 10:15
@Sokol142196 This error doesn't show up when running on localhost

**Comment by Sokol142196** [comment] 2023-11-29 10:29
> @Sokol142196 This error doesn't show up when running on localhost

Thank you,
@S2kael please check this issue on your device. If this situation cannot be reproduced, close the issue

**Comment by Thiendekaco** [comment] 2023-11-29 11:13
@Sokol142196 Error occurs simply because the browser lacks attributes, caused by the website's non-HTTP or non-HTTPS access, which compromises user safety

**Comment by Sokol142196** [comment] 2023-12-16 08:35
Version test: http://192.168.0.4:9000/

Please check the issues:

- [ ] Update UI
  - Expect: 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/7852f858-6c52-4fbc-ae4d-14ce7a389740)

- [ ] Handle case of click Back icon button on this page
  - Actual: Back to home
  - Expect: When click on "<" - Back button then navigate to the Settings screen

- [ ] Handle case visit Security setting screen after "back/back to home"
  Steps:
  1. Perform setting Camera permission
  2. On the Danger ahead screen then click on Back or Back to home
  3. Then, go to Security setting screen again
  4. Observe the screen displayed

  Actual: Show Danger ahead screen
  Expect: Show the Security setting screen with Camera access for QR is OFF

**Comment by Sokol142196** [comment] 2023-12-19 11:51
Validation passed
![2138-Validation](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/9a44311b-5417-4378-9bde-a19216929bc7)

**Closed by Sokol142196** 2023-12-19 11:51 UTC
